import { jsPDF } from 'jspdf';
import { generateQRDataURL } from './qrcode';

export interface CertificateData {
  id: string;
  name: string;
  degree: string;
  institution: string;
  year: string;
  txHash: string;
  issuedAt?: string;
  expiresAt?: string;
}

export async function generateCertificatePDF(data: CertificateData): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, w, h, 'F');

  // Border frame
  doc.setDrawColor(0, 255, 136);
  doc.setLineWidth(0.5);
  doc.rect(8, 8, w - 16, h - 16);
  doc.setDrawColor(0, 102, 255);
  doc.setLineWidth(0.3);
  doc.rect(11, 11, w - 22, h - 22);

  // Corner decorations
  const corners = [[14, 14], [w - 14, 14], [14, h - 14], [w - 14, h - 14]];
  corners.forEach(([x, y]) => {
    doc.setFillColor(0, 255, 136);
    doc.circle(x, y, 1.5, 'F');
  });

  // Header - VERIDICHAIN
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0, 255, 136);
  doc.text('VERIDICHAIN', 20, 25);

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('BLOCKCHAIN CREDENTIAL VERIFICATION', 20, 30);

  // Solana badge - top right
  doc.setFontSize(8);
  doc.setTextColor(0, 102, 255);
  doc.text('VERIFIED ON SOLANA DEVNET', w - 20, 25, { align: 'right' });

  // Divider line
  doc.setDrawColor(30, 30, 46);
  doc.setLineWidth(0.3);
  doc.line(20, 36, w - 20, 36);

  // Title
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text('CERTIFICATE OF VERIFICATION', w / 2, 55, { align: 'center' });

  // Subtitle
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 136);
  doc.text('This certifies that the following credential has been verified on the Solana blockchain', w / 2, 64, { align: 'center' });

  // Recipient name
  doc.setFontSize(22);
  doc.setTextColor(0, 255, 136);
  doc.text(data.name.toUpperCase(), w / 2, 82, { align: 'center' });

  // Degree
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(data.degree, w / 2, 92, { align: 'center' });

  // Institution
  doc.setFontSize(11);
  doc.setTextColor(136, 136, 136);
  doc.text(data.institution + '  ·  ' + data.year, w / 2, 100, { align: 'center' });

  // Divider
  doc.setDrawColor(30, 30, 46);
  doc.line(w / 2 - 40, 108, w / 2 + 40, 108);

  // Details grid
  const detailY = 118;
  const col1 = 20;
  const col2 = w / 2 + 10;

  doc.setFontSize(7);
  doc.setTextColor(85, 85, 85);
  doc.text('CREDENTIAL ID', col1, detailY);
  doc.setFontSize(10);
  doc.setTextColor(0, 255, 136);
  doc.text(data.id, col1, detailY + 6);

  doc.setFontSize(7);
  doc.setTextColor(85, 85, 85);
  doc.text('TRANSACTION HASH', col2, detailY);
  doc.setFontSize(9);
  doc.setTextColor(0, 102, 255);
  const displayTx = data.txHash.length > 30 ? data.txHash.slice(0, 15) + '...' + data.txHash.slice(-10) : data.txHash;
  doc.text(displayTx, col2, detailY + 6);

  doc.setFontSize(7);
  doc.setTextColor(85, 85, 85);
  doc.text('ISSUED DATE', col1, detailY + 16);
  doc.setFontSize(10);
  doc.setTextColor(200, 200, 200);
  doc.text(data.issuedAt ? new Date(data.issuedAt).toLocaleDateString() : new Date().toLocaleDateString(), col1, detailY + 22);

  doc.setFontSize(7);
  doc.setTextColor(85, 85, 85);
  doc.text('STATUS', col2, detailY + 16);
  doc.setFontSize(10);
  doc.setTextColor(0, 255, 136);
  doc.text('VERIFIED ON-CHAIN', col2, detailY + 22);

  if (data.expiresAt) {
    doc.setFontSize(7);
    doc.setTextColor(85, 85, 85);
    doc.text('EXPIRES', col1, detailY + 32);
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(new Date(data.expiresAt).toLocaleDateString(), col1, detailY + 38);
  }

  // QR Code
  try {
    const qrDataURL = await generateQRDataURL(data.id);
    doc.addImage(qrDataURL, 'PNG', w - 55, detailY - 4, 35, 35);
    doc.setFontSize(6);
    doc.setTextColor(85, 85, 85);
    doc.text('SCAN TO VERIFY', w - 37.5, detailY + 34, { align: 'center' });
  } catch (e) {
    console.error('QR generation failed', e);
  }

  // Footer
  doc.setDrawColor(30, 30, 46);
  doc.line(20, h - 25, w - 20, h - 25);
  doc.setFontSize(7);
  doc.setTextColor(68, 68, 68);
  doc.text('This certificate was generated by VeridiChain — Blockchain Credential Verification Platform', w / 2, h - 20, { align: 'center' });
  doc.text('Solana Frontier Hackathon 2026  |  Verify at veridichain.app/verify/' + data.id, w / 2, h - 15, { align: 'center' });

  // Save
  doc.save(`VeridiChain_Certificate_${data.id}.pdf`);
}
